config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'lists#index'

  resources :lists, except: [:index] do
    member do
      get :movie
    end

    resources :bookmarks, only: [ :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, presence: true
  validates :list, presence: true

  validates_uniqueness_of :list_id, :scope => [:movie_id]

end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def show
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(prms)

    if @bookmark.save
      redirect_to list_path(@bookmark.list), notice: 'bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
  end

  private

  def prms
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
before_action :find_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(prms)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @list.update(prms)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def find_list
    @list = List.find(params[:id])
  end

  def prms
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def lists
  end

  def index
  end

  def show
  end

  private
  def prms
    params.require(:list).permit(:titlte, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/:create,.html.erb
<h1>Bookmarks#:create,</h1>
<p>Find me in app/views/bookmarks/:create,.html.erb</p>

app/views/bookmarks/:destroy.html.erb
<h1>Bookmarks#:destroy</h1>
<p>Find me in app/views/bookmarks/:destroy.html.erb</p>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#:create,</h1>
<p>Find me in app/views/bookmarks/:create,.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#:destroy</h1>
<p>Find me in app/views/bookmarks/:destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Create your bookmarch</h1>

<%= simple_form_for @bookmark, url: list_bookmarks_url do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.association :list %>
  <%= f.button :submit %>
<% end %>

app/views/bookmarks/show.html.erb
<h1>bookmark</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="row">
    <div class="col-xs-12">
      <nav class="navbar navbar-light bg-light px-4">
      <span class="navbar-brand mb-0 h1">The Watchlist 👀</span>
      <%=link_to "Add a new list", new_list_url, class: "pull-right btn btn-primary"%>
      </nav>
    </div>
  </div>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container form-control">

  <%= simple_form_for(@list) do |f|  %>
  <h3 class="pb-4">Create your list 👇🏻</h3>
    <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
      </div>
        <%= f.button :submit, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/delete.html.erb
<h1>Lists#delete</h1>
<p>Find me in app/views/lists/delete.html.erb</p>

app/views/lists/index.html.erb
  <div class="col-sm-12 d-flex flex-wrap flex-gap-2">
    <% @lists.each  do |list| %>
    <div class="card" style="width: 18rem;">
    <%=cl_image_tag list.photo.key, crop: :fill %>
    <div class="card-body">
    <h5 class="card-title"><%=list.name%> </h5>
        <%= link_to "Learn more", list_path(list), class: 'btn btn-primary'%>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="my-6">
  <%= render "form", flat:@flat %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>


<% if @list.movies.length > 0 %>
    <div class="col-sm-12 d-flex">
      <% @list.movies.each  do |movie| %>
          <section class=" my-5" style="max-width: 23rem;">
            <div class="card">
              <div class="card-body d-flex flex-row">
                <div>
                  <h5 class="card-title font-weight-bold mb-2"><%=movie.title%></h5>
                </div>
              </div>
              <div class="bg-image hover-overlay ripple rounded-0" data-mdb-ripple-color="light">
                <img class="img-fluid" src=<%="https://image.tmdb.org/t/p/original/#{movie.poster_url}"%>
                  alt="Card image cap" />
                <a href="#!">
                  <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                </a>
              </div>
              <div class="card-body">
                <p class="card-text collapse" id="collapseContent">
                <%=movie.overview%>
                </p>
                <div class="d-flex justify-content-between">
                  <a class="btn btn-link link-danger p-md-1 my-1" data-mdb-toggle="collapse" href="#collapseContent"
                    role="button" aria-expanded="false" aria-controls="collapseContent">Read more</a>
                  <div>
                    <i class="fas fa-share-alt text-muted p-md-1 my-1 me-2" data-mdb-toggle="tooltip"
                      data-mdb-placement="top" title="Share this post"></i>
                    <i class="fas fa-heart text-muted p-md-1 my-1 me-0" data-mdb-toggle="tooltip" data-mdb-placement="top"
                      title="I like it"></i>
                  </div>
                </div>
              </div>
            </div>
          </section>
    <% end %>
    </div>
  </div>

<% end %>

<hr>
<div class="d-flex mb-4">
<%= link_to "🔙 back to your lists", root_path, class: "btn btn-dark"%>
<%= link_to "Create New Bookmark", new_list_bookmark_url(@list), class: "btn btn-success" %>
<%= link_to "Delete List", root_path,  method: :delete, class: "btn btn-danger"%>

</div>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>

app/views/movies/lists.html.erb
<h1>Movies#lists</h1>
<p>Find me in app/views/movies/lists.html.erb</p>

app/views/movies/show.html.erb
<h1>Movies#show</h1>
<p>Find me in app/views/movies/show.html.erb</p>